### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by bsideup** [Kotlin/kotlin-coroutines#46] opened 2016-05-30 08:34 UTC
Hi!

Please, take into the account that coroutines are really useful as "delayed executable" feature, where you can serialize your continuation and resume it later, after deserialization (i.e. from DB)

Right now it's possible (more or less), with some limitations, i.e. `controller` field in generated code is private, so, once it's deserialized, we have to use reflection to set it. I see "entryPoint" in examples, but not in compiled code - was it removed? It's needed :)

Since it works already, I hope that this feature will not disappear, so this issue will be used to track the status of serialization of coroutines.

**Comment by abreslav** [comment] 2016-05-31 08:39
This looks like a duplicate of #28

**Closed by abreslav** 2016-05-31 08:39 UTC
